# Generated by Django 6.0.2 on 2026-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saída', 'Saída'), ('transferencia', 'Transferência')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
            ],
        ),
    ]
