# Generated by Django 6.0.2 on 2026-02-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoria'),
            preserve_default=False,
        ),
    ]
