# Generated by Django 6.0.3 on 2026-03-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_transacao_comprovante_alter_transacao_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
